### ISSUE TITLE
README - :x: and :white_check_mark: emojis not used

### ISSUE THREAD

**Issue by srvxid** [SoftwareEngineeringToolDemos/FSE-2012-ATA#6]
For source code/binary, emojis not used.
Assigning to myself.

**Comment by srvxid** [comment]
Pull request created.

**Comment by seelder** [comment]
Still needs third emoji

**Comment by srvxid** [comment]
I don't think an emoji for slightly modified version is needed for tools that don't need it, especially an unworkable.

**Comment by seelder** [comment]
I've included it for visual consistency. I made a similar comment (and suggested update) on the tool I reviewed, although admittedly that one was "unworkable" despite having access to the source code.
